
export const dummyBlogs = [
  {
    _id: "1",
    title: "Getting Started with Next.js 14",
    slug: "getting-started-with-nextjs-14",
    excerpt: "Learn the fundamentals of Next.js 14 and build modern web applications with React.",
    author: "John Doe",
    date: "March 15, 2024",
    tags: ["Next.js", "React", "JavaScript"],
    image: "/images/blog-thumbnails/nextjs-guide.jpg",
  },
  {
    _id: "2",
    title: "Mastering CSS Grid and Flexbox",
    slug: "mastering-css-grid-flexbox",
    excerpt: "A comprehensive guide to modern CSS layout techniques for responsive design.",
    author: "Jane Smith",
    date: "March 12, 2024",
    tags: ["CSS", "Web Design", "Frontend"],
    image: "/images/blog-thumbnails/css-guide.jpg",
  },
  {
    _id: "3",
    title: "JavaScript ES2024 New Features",
    slug: "javascript-es2024-features",
    excerpt: "Explore the latest JavaScript features and how they can improve your development workflow.",
    author: "Mike Johnson",
    date: "March 10, 2024",
    tags: ["JavaScript", "ES2024", "Programming"],
    image: "/images/blog-thumbnails/js-features.jpg",
  },
  {
    _id: "4",
    title: "Building RESTful APIs with Node.js",
    slug: "building-restful-apis-nodejs",
    excerpt: "Step-by-step guide to creating robust and scalable APIs using Node.js and Express.",
    author: "Sarah Wilson",
    date: "March 8, 2024",
    tags: ["Node.js", "API", "Backend"],
    image: "/images/blog-thumbnails/nodejs-api.jpg",
  },
  {
    _id: "5",
    title: "React Hooks Deep Dive",
    slug: "react-hooks-deep-dive",
    excerpt: "Master React Hooks with practical examples and advanced patterns.",
    author: "David Lee",
    date: "March 5, 2024",
    tags: ["React", "Hooks", "Frontend"],
    image: "/images/blog-thumbnails/react-hooks.jpg",
  },
  {
    _id: "6",
    title: "MongoDB Atlas: Cloud Database Guide",
    slug: "mongodb-atlas-guide",
    excerpt: "Learn how to set up and manage MongoDB Atlas for your web applications.",
    author: "Emily Brown",
    date: "March 3, 2024",
    tags: ["MongoDB", "Database", "Cloud"],
    image: "/images/blog-thumbnails/mongodb-guide.jpg",
  },
];
